### ISSUE TITLE
The PnL section in Analytics not showing GBP/JPY info.

### ISSUE THREAD

**Issue by TejavardhanP** [AdaptiveConsulting/ReactiveTraderCloud#1674]
![image](https://user-images.githubusercontent.com/73316911/96937354-d46aa500-14bf-11eb-8bdf-a1f6c07b23e0.png)

**Comment by garyadaptive** [comment]
Thank you for raising this.

The trading execution engine has a number of custom behaviors for different instruments: in the case of GBP/JPY, we reject all trades in order to demonstrate an unhappy path. Consequently, we are never able to show a position for this currency pair. For clarity, see the implementation here: https://github.com/AdaptiveConsulting/ReactiveTraderCloud/blob/master/src/server/dotNet/Adaptive.ReactiveTrader.Server.TradeExecution/TradeExecutionEngine.cs#L91.
