### ISSUE TITLE
Connection status UI updates 

### ISSUE THREAD

**Issue by LeeCampbell** [AdaptiveConsulting/ReactiveTraderCloud#221]
There are some odd artifacts on the top right of the app

![image](https://cloud.githubusercontent.com/assets/981443/13723212/2e7a3bd0-e899-11e5-9e1f-0d4dc421f405.png)

It appears to be a histogram and 5 pictures of the digit 1. There is no visual clues (e.g. Tooltips) as to what these are. Interacting with them appears to do nothing (hover, click, double click, right click, drag). Also executing trades doesn't seem to affect them.

If these are supposed to be surfacing some information (notifications count, QoS, trade count etc), then give the user some feedback that this is what these are for.

**Comment by KeithWoods** [comment]
They are meant to be connection status details for each connected service node and oddly the histogram represents connection to the broker (It what? ... exactly!).  Typically I'd expect these at the lower right of a trading app. 

I suggest we move them to a footer, and add some UX that clearly defines what they do rather than has the user guessing.

UX to follow.

**Comment by KeithWoods** [comment]
do #106 first

**Comment by fdore** [comment]
Connection status has been refactored. Closing this ticket for now. Can create a new ticket when we get a proper design for it.
