### ISSUE TITLE
StartServices.bat results in error to connect to a broker

### ISSUE THREAD

**Issue by tstojecki** [AdaptiveConsulting/ReactiveTraderCloud#498]
I followed the setup on win as documented here:
https://github.com/AdaptiveConsulting/ReactiveTraderCloud/blob/master/docs/setup/windows-setup.md

In the  last step, under Run Services, it says to run StartAll.bat, however that file isn't there anymore. What is in the server directory is StartServices.bat. Running that results in:

No connection could be made because the target machine actively refused it [ws://localhost:8085/ws]

I have tried different ports and disabled the firewall for test.

I haven't installed crossbar, but was under the impression that I can run it without it in dev mode with a in memory broker. Is my understanding correct? If so, anything obvious I may have missed in the setup?

**Comment by qooroo** [comment]
That's indeed an error - thanks for raising!

The in-memory broker was removed during the conversion to .NET Core from mono. So currently you do have to run a standalone broker and standalone eventstore.

I'll update the docs and I'll take a look at adding back the in-memory broker and eventstore separately if people prefer doing it that way.

The easiest option for now is to run them locally with docker.

pull the images from here:
https://hub.docker.com/r/reactivetrader/broker
https://hub.docker.com/r/reactivetrader/eventstore

then run
```
docker run -d --net=host reactivetrader/broker:0.0
docker run -d --net=host reactivetrader/eventstore:0.0
```

StartServices.bat should then work.

**Comment by tstojecki** [comment]
Ok, makes more sense now, thanks @qooroo I will go ahead and get the broker set up separately then.

For dev and test scenarios, seems like an in-memory broker might be useful, assuming it is not too much trouble to maintain. Would also help with a newbie install - crossbar on win does require a manual py install and config. 
As you said though, much easier with docker.

**Comment by tstojecki** [comment]
Will leave it open - feel free to close when the docs are updated.

**Comment by sirockin** [comment]
I've tried running the broker and eventstore images from Docker (Quickstart Terminal) as advised by @qooroo and I still get exceptions thrown from launcher when running StartServices.bat (see below). I'm a Docker newbie but I'm guessing something needs to be done to expose the broker service endpoint from the docker container to the localhost. 
`
2016-08-26 12:52:22 [Information] Trying to connect to broker "ws://localhost:8080/ws"
2016-08-26 12:52:23 [Error] A connection error occured
System.AggregateException: One or more errors occurred. (No connection could be made because the target machine actively
 refused it 127.0.0.1:8080) ---> System.Net.Internals.SocketExceptionFactory+ExtendedSocketException: No connection coul
d be made because the target machine actively refused it 127.0.0.1:8080
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.TcpClient.EndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.TcpClient.<>c.<ConnectAsyncCore>b__62_1(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction,
Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
`

**Comment by michaelkacher** [comment]
@qooroo I ran the two docker images (broker and eventstore) you mentioned above and the StartService.bat does not work. It is the same issue with not being able to connect.  I tried adding the -p flag when running the docker image but am not sure if I am trying to expose the correct ports.  Do you know what ports we should try to map?

I am using Docker for Windows to run the images.

**Comment by Yosiempresafo** [comment]
Hi! I have the same problem. 
This issue was reopened on 17 Aug 2016 and is yet to be solved - can someone follow up on this please? :pray:
Thanks!

**Comment by marcoaal** [comment]
@qooroo I have the same problem, I'm trying to run the server on Windows but I didn't find the "StartAll.bat" file then I selected the "StartServices.bat". I'm using the terminal in my local computer because I don't want to use Docker

**Comment by Pedroz14** [comment]
I can't run the program from source code too, I have heard that docker just make things worse at the end. Will there be any documentation more regarding the installation than the included in readme.md?

**Comment by qooroo** [comment]
Firstly an apology - we've dropped the ball.a bit on this as various people have had less time.

We are actively working on a change on how we run locally. This will be using minikube to simulate as closely as possible the deployed kubernetes infrastructure.

Once that's done I will then merge the changes from the `vs2017` branch and we should be up to date on the server side.

We want to save people from having to manually install crossbar and eventstore locally just to run the app, hence the drive to dockerise. However if you do want to install everything separately we will also update the docs for that.

Watch this space!

**Comment by larstbone** [comment]
Using Docker for Windows with Linux containers exhibits the same problem.  The Broker and EventStore containers are being built and published daily - wonder if there's any movement on this.

**Comment by tdeheurles** [comment]
The docker build on windows is fixed and documentation updated at https://github.com/AdaptiveConsulting/ReactiveTraderCloud/tree/master/docs/deployment.

Closing for now. Do not hesitate to ask for reopen or create new issue if problem persist.
