### ISSUE TITLE
Improve event sourcing patterns

### ISSUE THREAD

**Issue by mattbarrett** [AdaptiveConsulting/ReactiveTraderCloud#550]
Introduce a process manager for trade execution to better model real-world usage of event sourcing.

**Comment by daniel-smith** [comment]
WIP is on the process branch. See https://github.com/AdaptiveConsulting/ReactiveTraderCloud/compare/dev...process.

An issue I'm seeing is that the spot tiles are now immediately moving to the "sold" state. This is because the call to book a trade is designed as "request / response", and prior to having a process manager, the delay between the pending and done states was done as part of that request / response. Now the response immediately returns a trade in the pending state, and the transition to done / rejected is done via the process manager. Will need to find a way to fix this.

**Comment by daniel-smith** [comment]
Regarding the above issue with the tiles, I think what we really want to do is subscribe to a stream of trade status by trade ID.
