### ISSUE TITLE
External docked tiles can't be undocked

### ISSUE THREAD

**Issue by zeala** [AdaptiveConsulting/ReactiveTraderCloud#618]
Clicking on the 'undock' icon doesn't undock the tile.

![image](https://user-images.githubusercontent.com/12033798/35329537-269381e6-00f8-11e8-9ddd-93b4219ba842.png)

**Comment by dwalker11** [comment]
After some investigation, I discovered that the problems of this issue were two-fold. The CSS positioning of elements did not allow the user to click on the 'undock button'. However, once you resolve that issue you'll discover that clicking on the 'undock button' has no effect on the docked elements.

The issue lies with these few lines of code:
```
DockingManager.prototype.onUndock = function(message) {


  var name = message.windowName;

  for (var i = 0; i < windows.length; i++) {

    if (windows[i].name === name) {

      windows[i].leaveGroup();
    }
  }
};
```

The `windowName` property extracted from `message` parameter is not in the expected format required for this function to work properly. Updating the format of the spotTile's title property seems to resolves this issue.
